version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: mic-postgres
    environment:
      POSTGRES_DB: micdb
      POSTGRES_USER: mic
      POSTGRES_PASSWORD: micpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: mic-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mic.local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
